# nixpacks.toml

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.bcmath", "php83Extensions.gd", "nginx", "nodejs_20"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "chmod -R 777 storage bootstrap/cache",
    "composer install --optimize-autoloader --no-dev",
    "npm install",
    "npm run build",
    "php artisan optimize:clear"
]

[start]
cmd = "php artisan migrate --force && nginx -c /assets/nginx.conf"